### ISSUE TITLE
1. static 활용 문제

### ISSUE THREAD

**Issue by HyunGyu-Lee** [HyunGyu-Lee/basic-java#2]
## 문제
무기 클래스 모델링하기

1. 무기 클래스는 공격력, 강화수치, 각인수치로 구성됨
2. 공격력과 강화수치는 무기 단위로 관리되고, 각인수치는 무기 전체 공유됨
3. 무기의 총 공격력 계산은 공격력 + ((강화수치 + 각인수치) * 10) 으로 산정
4. 무기 클래스에서 무기 생성, 무기 총 공격력 획득 기능, 강화 기능, 각인 기능을 제공해야함

모델링(클래스 생성자 변수 메소드 정의)를 하고 댓글로 남길 것

**Comment by KimPro-KR** [comment]
## 클래스 : 무기 클래스
   - 멤버변수 : 공격력, 강화 수치 (무기(객체) 별 적용)
   - Static 변수 : 각인수치 (무기 전체 공유)
## 생성자 
   - 공격력, 강화수치
## 메소드 
   - get메소드 2개
   - 무기 총 공격력 획득(무기 객체 생성)
   - 강화 기능
   - 각인 기능

**Comment by KimPro-KR** [comment]
> ## 문제
> 무기 클래스 모델링하기
> 
> 1. 무기 클래스는 공격력, 강화수치, 각인수치로 구성됨
> 2. 공격력과 강화수치는 무기 단위로 관리되고, 각인수치는 무기 전체 공유됨
> 3. 무기의 총 공격력 계산은 공격력 + ((강화수치 + 각인수치) * 10) 으로 산정
> 4. 무기 클래스에서 무기 생성, 무기 총 공격력 획득 기능, 강화 기능, 각인 기능을 제공해야함
> 
> 모델링(클래스 생성자 변수 메소드 정의)를 하고 댓글로 남길 것
