### ISSUE TITLE
3. 동물 클래스 모델링에 추상 클래스 사용하기

### ISSUE THREAD

**Issue by HyunGyu-Lee** [HyunGyu-Lee/basic-java#4]
[동물 클래스 모델링 문제 참조](https://github.com/HyunGyu-Lee/basic-java/issues/3)

이전에 했던 동물 클래스 (Animal, Cat, Dog) 모델링 결과에 추상 클래스를 사용한다.

달리기 (run) 메소드를 추상화하고, 각 하위 클래스에서 내용을 구현하도록 한다.

**Comment by KimPro-KR** [comment]
Animal를 추상 클래스로 만들고 그안에 run 이라는 추상 메소드 생성 하여
Dog,Cat클래스에서는 Animal클래스를 상속받고 run 메소드를 호출하여 내용을 재정의 한다.
