### ISSUE TITLE
4. 자동차, 엔진 클래스 모델링

### ISSUE THREAD

**Issue by HyunGyu-Lee** [HyunGyu-Lee/basic-java#5]
## 자동차 클래스
- 자동차명
- 엔진
- 시동걸기 

## 엔진 인터페이스
- 엔진 버전 획득
- 엔진 이름 획득
- 엔진 구동

엔진 종류는 가솔린 엔진, 디젤 엔진 2종

자동차 클래스에서는 가솔린 / 디젤 상관없이 엔진을 설정할 수 있고, `시동걸기` 시 엔진이 `구동`됨.

자동차 `시동걸기` 시 엔진 구동전에 엔진 버전과 엔진 이름을 출력해줌

**Comment by KimPro-KR** [comment]
1. 추상클래스
  - 공통적인 기능을 하는 객체들의 추상화
  - 일반적인 추상화 및 상속에 더 초점을 둔다
  - 여러 클래스들의 공통점을 찾아 추상화 시켜서 사용하는 것이 좋을 때 사용
  - public 이외의 접근 제어자 사용시
  - 추상클래스를 상속받은 서브클래스는 다른 클래스를 상속 받을 수 없다.

2. 인터페이스
  - 구현하는 모든 클래스에 대해 특정메소드가 반드시 존재하도록 강제하는 역할
  - 구현 객체가 같은 동작을 한다는 것을 보장하기 위함
  - 다중 상속 가능
  - 클래스(public static final), 메소드(public abstract) 가 기본적으로 있음
  - 인터페이스를 구현하는 어떤 클래스는 다른 여러개의 인터페이스들을 함께 구현가능
  - 서로 관련성 없는 클래스들이 인터페이스를 구현하게 되는 경우 사용
  - 다중상속을 허용하고 싶은경우 사용
  - 특정 데이터  타입을 명시하고 싶은데 어디서 그 행동이 구현되는지는 신경쓰지 않음

**Comment by HyunGyu-Lee** [comment]
@KimPro-KR 
위에 이해한 내용 기반으로 `Engine` 인터페이스 및  `DieselEngine`, `GasolineEngine` 클래스 사이에
`AbstractEngine`이라는 추상클래스를 추가하고, 엔진 공통 기능 구현하도록 변경

**Comment by KimPro-KR** [comment]
클래스들의 공통적인 부분을 포함하는 추상클래스를 생성해서 Engine 인터페이스를 implements 한다.
추상클래스 내에서는 인터페이스 내부의 메소드를 재정의 해준다.
추상클래스에서 엔진이름과엔진버전(엔진들의 공통 속성)을 파라미터로 하는 생성자를 생성하고,
상속받는 서브 클래스에서 super를 사용하여 각 엔진의 이름과버전으로 생성자를 생성한다.

**Comment by HyunGyu-Lee** [comment]
@KimPro-KR 
- 엔진에 `정비` 기능 추가
    - 가솔린 / 디젤 엔진 별 정비 방식이 다름
- 엔진 `종료` 기능 추가
    - 엔진 종류에 상관없이 종료 기능은 동일

- 자동차에 `시동끄기` 기능 추가 후 이때 엔진 `종료` 시킬 것

**Comment by HyunGyu-Lee** [comment]
@KimPro-KR 

- 엔진 정비 방식이 다르게 때문에, `engineFix` 메소드를 가솔린 / 디젤 엔진 클래스 수준에서 `구현 (@Override)` 해야함.
- 엔진 종료 기능은 `엔진`의 역할인데 `자동차`에 구현함
