### ISSUE TITLE
5. java.lang, java.util 패키지 공부

### ISSUE THREAD

**Issue by HyunGyu-Lee** [HyunGyu-Lee/basic-java#6]
강의에서 공부한 클래스가 뭔지, 어떤 내용을 학습했는지 댓글로 달아주면,

내가 제대로 이해했는지 확인하고, 그 클래스 활용해서 할 수 있는 예제를 내줄 예정

## 학습한 클래스 정리
- Object
- System
- Class
- String
- Byte, Short, Character, Integer, Float, Double, Boolean, Long
- Math
- HashSet, Hashtable, HashMap

**Comment by KimPro-KR** [comment]
1. 자바 API(Java Application programming Interface)
    - 자바에서 제공하는 클래스 및 인터페이스 모음
    - 웹페이지 형태로 제공
2. java.lang : 자바프로그램의 기본적인 클래스를 담은 패키지(import 없이 사용)
    1) Object : 모든 자바클래스의 최상위클래스, 모든 클래스는 object 클래스의 자식이거나 자손클래스이다.
    2) System : 자바프로그램이 실행하는 운영체제의 정보
                표준입력장치, 표준출력장치, 자바프로그램 종료를 위한 가상 기계종료, 메모리정리를 위한 쓰리게 수집
    3) Class : 작성한 바이트코드 파일을 메모리에 로딩할 때
    4) String : 문자열 저장
    5) wrapper : Byte, Short, Character, Integer, Float, Double, Boolean, Long
                 기본타입의 값을 객체로 만들때 사용
    6) Math : 수학함수 사용


1) Object 클래스
    - 객체비교(equals(비교객체))
    - 매개변수는 비교객체, 현재객체와 비교하여 Boolean 타입으로 리턴
    - equals() 메소드를 재정의하는 경우
        * 두 객체가 필드값이 같은 동등객체인경우
        * 두객체의 필드가 모두 같으면 true
        * 두객체가 같은 종류여야 하고 필드값이 같은지 다른지의 여부 확인
        * equals() 메소드로 value 인스턴스가 가지고 있는 value 값을 비교하기위해 사용

2) 객체 해시코드 (hashcode())
    - 객체를 식별하는 하나의 정수밧
    - Object의 객체 해시코드 메소드는 객체 메모리 번지를 이용하여 만듬 => 모든 객체마다 해시코드 리턴값은 다른 값
    - 객체가 다를 경우 논리적으로 동등하게 만들어줄 때 사용
        1. 해시코드로 객체비교
        2. equals()로 필드값 비교
        위에 두개가 참인경우 동등객체
    - equals() 메소드만 재정의 할 경우에는 키값이 같아도 필드값이 틀리면 다른값으로 판단
      hashCode() 메소드 재정의 후 키값 중복 제거
    - HashSet, Hashtable, HashMap
    - HashMap
        *형식
          키  키  키  키
          값  값  값  값
        * 사용법
            - HashMap<키,값> hashMap = new HashMap<키,값>();
        * 특징
            - 문자열이 동일한 키는 중복되어 저장되지 않는다.
            - import java.util.HashMap; 해줘야됨   <<<< java.lang 인데 왜 import를 해줘야할까...? (질문)
            - 같은 키가 나오게 되면 이전키와 값은 없애고 새로운 키와 값을 저장

**Comment by HyunGyu-Lee** [comment]
@KimPro-KR 
- import문 보면 알수 있지만 HashMap 클래스는 java.util에 존재함. 왜 java.lang 패키지라고 생각했는지?

**Comment by KimPro-KR** [comment]
아.. 앞에 같은 Hash가 적혀있어서 Hashcode()랑 같은 분류인줄 알고 java.lang이라고 생각햇엇읍니다

**Comment by HyunGyu-Lee** [comment]
@KimPro-KR 
java.util.HashMap은 클래스고, hashcode()는 java.lang.Object 클래스 안에 선언되어있는 메소드임

**Comment by KimPro-KR** [comment]
금일 공부 내용 작성합니다.
인강으로 듣고있는데.. 내용이 심오하네요..
지금까지 한거랑 느낌도 틀리고 어렵습니다..

3)객체문자정보 (tostring())
    - object 클래스의 tostring() 메소드는 객체의 문자정보 리턴
        * 기본적으로 =>  "클래스이름@16진수해시코드" 로 구성된 무자 정보
    - tostring() 메소드를 재정의 하는 경우
        * 유익한 정보를 리턴하기 위해

4) System 클래스
    - 모든 필드와 메소드는 정적필드 및 메소드로 구성
    - exit()  : 프로그램 종료
        - JVM 강제 종료 
        - 지정하는 int 매개값을 종료 상태값으로. ex> exit(0);
    - currentTimeMills();  ,   nanoTime();
        - 정밀한 시간, long 값 리턴
5) Class 클래스
    - 자바는 클래스와 인터페으싀 메타데이터를 Class 클래스로 관리
        * 메타데이터 : 타입이름 및 파일경로 정보, 필드정보, 생성자 정보, 메소드 정보

    - 클래스 객체 얻기(getClass(), forName())
        * 클래스로부터 얻는 방법
            - Class 변수명 = 클래스이름.class
            - Class 변수명 = Class.forName("패키지 . . . 클래스이름")
        * 객체로부터 얻는 방법
            - Class 변수명 = 참조변수.getClass();
    - For Example
        1. Car car = new Car();   // car 라는 Car 객체 생성
        2. Class clazz = Car.getClass();    // Car 클래스 값을 클래스변수 class 에 대입
        3. 출력 테스트
            System.out.println(clazz.getName());    // 클래스 전체 경로 출력
            System.out.println(clazz.getSimpleName());  // 클래스 이름 출력
            System.out.println(clazz.getPackage().getName());   //  패키지 이름 출력

**Comment by HyunGyu-Lee** [comment]
@KimPro-KR 
1. Object 클래스의 `toString`, `equals`, `hashcode` 메소드
    - 예시 클래스 2개를 만들어서 하나는 아무작업도 하지않고, 하나는 위 3메소드 재정의한 후 Main에서 각각 실행해보기

2.  System 클래스
    - `currentTimeMills()` 메소드 호출 결과를 https://currentmillis.com/ 사이트에서 변환해 확인해보기

3. Class 클래스는.. 우선 저런 것들이 있구나~ 하는 정도로 넘어갈것

**Comment by KimPro-KR** [comment]
금일 공부한 내용입니다.

1. String 클래스
    1) String 생성자 => 직접 String 객체 생성
       ex> String str = "자바";
    
    2) 형식
        - 배열 전체를 String 객체로 생성
        ex > String str = new String(byte[] bytes);
        - 지정한 문자셋으로 디코딩(배열=>문자열)
        ex > String str = new String(byte[] bytes, String charsetName);
        - 배열의 offset 인덱스 위치부터 length 만큼 String 객체로 생성(지정한 위치에서 length만큼)
        ex > String str = new String(byte[] bytes, int offset, int length);
        - 지정한 문자셋으로 디코딩
        ex > String str = new String(byte[] bytes, int offset, int length, String charsetName);


    3) 메소드
        - charAt() : 문자열에서 매개변수 값 위치의 문자
        - equals() : 두 문자열을 비교
        - getBytes() : byte[]로 리턴
        - toLowerCase() : 소문자로
        - toUpperCase() : 대문자로
        - trim() : 문자열의 앞뒤 공백 제거
        - indexof() : 문자열에서 주어진 문자열의 위치
        - length() : 총 문자의 수

    4) charAt() 메소드 : 매개값으로 주어진 인덱스의 문자를 리턴
        - ex > String str = "자바 프로그래밍";
               Char char = str.charAt(3);    // 결과값 : "프"
    
    5) equals() : 문자열비교
        - ex > String str1 = new String("abc");
               String str2 = "abc";
               String str3 = "abc";

               str1 == str2 // false
               str2 == str3 // true
               str1.equals(str2) // true
               str2.equals(str3) // true

    6) getBytes() : 바이트 배열로 변환
        - ex > byte[] byte = "문자열".getBytes();
        - 인코딩(문자열->배열)  ex> byte[] bytes = str.getBytes();
        - 디코딩(배열->문자열)  ex> String str = new String(bytes);

**Comment by KimPro-KR** [comment]
1. String 클래스
    - String 생성자 : String 객체 생성
        ex> String str = "자바";
    
    - 배열 전체를 String 객체로 생성
        String str = new String(byte[] bytes);
    - 지정한 문자셋으로 디코딩
        String str = new String(byte[] bytes, String charasetName);
    - 배열의 offset 인덱스 위치부터 length 만큼 String 객체로 생성 => 지정한 위치에서 어디까지할지
        String str = new String(byte[] bytes, int offset, int length);
    - 지정한 문자셋으로 디코딩
        String str = new String(byte[] bytes, int offset, int length, String charsetName);

        인코딩 : 문자열 => 배열
        디코딩 : 배열 => 문자열

    * 메소드
        - charAt():지정된 위치의 문자
        - equals():두문자열 비교
        - getBytes():byte[]로 리턴
        - indexOf():문자열에서 주어진 문자열의 위치
        - length():문자열 길이
        - toLowerCase(): 소문자로
        - toUpperCase(): 대문자로
        - trim(): 앞뒤 공백 제거

    1) charAt() : 매개값으로 주어진 인덱스의 문자를 리턴
        ex> String str = "자바 프로그래밍";
            Char char = str.charAt(3);
    2) equals() : 문자열비교 => 연산자로 사용 할 경우 원하지 않는 결과 값이 나올 수 있다.
        ex> String str1 = new String("ab");
            String str2 = "ab";
            String str3 = "ab";
            str1==str2 //false 번지가 틀림
            str2==str3 //true 번지가 같음
            str1.equals(str2) =>  true

    3) getBytes() : 바이트 배열로 변환
        ex> byte[] bytes = "문자열".getBytes();
    
    4) indexOf() : 매개값으로 주어진 문자열이 시작되는 인덱스 리턴
        => 매개값으로 주어진 문자열이 포함 되어있지 않을 시 -1 값 리턴
        ex> String str = "자바 프로그래밍";
            int index = str.indexOf("프로그래밍");
            // 결과 : int index = 3

            if(문자열.indexOf("찾는문자열)!=-1{})
            if(문자열.contains("찾는문자열")){}
    5) length() : 문자열 길이
        ex> int length = 문자열.length();
    
    6) replace() : 문자열 대치(원본 문자열 변경이 아닌 새로운 문자열로 리턴)
        ex> String old = "자바 프로그래밍"
            String new = old.replace("자바","JAVA");
            System.out.println(new);  // JAVA 프로그래밍  출력
    7) substring() : 문자열 잘라내기
        ex> String ssn = "1928490-2948719034";
            String newSsn = ssn.substring(0,6);
            System.out.println(newSsn);   // 1928490 출력
    8) toLowerCase(),toUpperCase() : 소문자로변경, 대문자로변경
    9) trim() : 문자열 앞뒤 공백 제거
    10) valueOf() : 문자열 변환
        - 기본타입의 값을 문자열로 변환
        - 정벅메소드
        ex> String str1 = String valueOf(10);
            String str2 = String valueOf(10.5);
            String str3 = STring valueOf(true);


2. Wrapper 클래스
    1) 포장 객체
        - 기본타입의 값을 내부에 두고 포장
        - 포장하고 있는 기본 타입 값은 외부에서 변경 할 수 없음
        - int => Integer , double => Double  많이 사용함 
    2) Boxing/Unboxing
        - Boxing : 기본타입 -> 포장객체
        - Unboxing : 포장객체에서 기본타입의 값을 얻어내는 과정
        ex> Integer obj1 = new Integer(100);  // Boxing
            int value = obj1.intValue();       //Unboxing
    3) 자동 Boxing/Unboxing
        - 포장클래스 타입에 기본값이 대입 될 경우 자동 박싱
            ex> Integer obj = 100;
        - 기본 타입에 포장 객체가 되입되는 경우 자동 언박싱
            ex> int value = obj; // obj라는 wrapper객체 안에 있는 값을 끌어내어 value에 대입하는것임
    4) 문자열을 기본타입 값으로 변환
        - 포장클래스로 문자열을 기본타입 값으로 변환
        - parse + 기본타입이름
        ex> int value1 = Integer.parseInt("10");
            double value2 = Double.parseDouble("3.14");
    5) 포장 값 비교
        - 포장객체는 내부값을 비교하기 위해 == 또는 !=를 사용하지 않는게 좋다
            ex> Integer obj1 = 300;   // 자동 박싱
                Integer obj2 = 300;
                obj1==obj2 // 결과값은 false => obj1과 obj2는 포장객체로 각각의 객체 번지가 틀리므로 false 리턴
                equal 을 써야 값을 비교 가능
        - 예외
            int,short,byte : -128 ~ 127
            ex> Integer obj1 = 120;
                Integer obj2 = 120;
                obj1 == obj2 // -128~127 사이에 포함된 값이므로 안에 값을 비교하여 true 값이 출력된다.

**Comment by KimPro-KR** [comment]
3. Math 클래스 
    - 수학계산에 사용
      1) Math.abs() : 매개값의 절대값 계산
      2) Math.ceil() : 매개값의 올림값 계산
      3) Math.floor() : 매개값의 내림값 계산
      4) Math.max() : 매개값 중 최대값
      5) Math.min() : 매개값 중 최소값
      6) Math.random() : 랜덤값 
          ex> double num = Math.random();   -> num 은 0.0 이상 1.0 미만의 double 값
      7) Math.rint() : 매개값의 가까운 실수 값
      8) Math.round() : 매개값 반올림 계산 (long 타입 값으로 리턴)
      9) 정수형 난수 구하기
          ex > int num = (int)(Math.random()*10)+1;
      10) 주사위 랜덤값 구하기
          ex > int dice = (int) (Math.random()*6)+1;

**Comment by KimPro-KR** [comment]
4. Date 클래스
    - 날짜와 시간정보를 저장하는 클래스 (import java.util.Date)
    - 객체간 날짜정보를 주고 받을 때 매개변수나 리턴타입으로 주로 사용
    - 원하는 타입(실사용하는타입)으로 하고싶은 경우 SimpleDateFormat 사용(import java.text.SimpleDateFormat)
    - format() 메소드 호출
        ex> Date date = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("날짜형식");
            String time = sdf.format(date);
            System.out.println(time);

5. Calendar 클래스
    - import java.util.Calendar;
    - 달력을 표현한 클래스로 운영체제의 날짜 및 시간 기준으로 다양한 정보를 얻을 수 있음
    - 추상 클래스 이므로 new 연산자를 사용하여 인스턴스 생성이 불가
    - getInstance() 메소드 이용하여 Calendar 하위 객체 얻을 수 있음
        ex> Calendar cal = Calendar.getInstance();
            int year = cal.get(Calendar.YEAR);
            int week = cal.get(Calendar.WEEK);

**Comment by HyunGyu-Lee** [comment]
@KimPro-KR 

- Math클래스의 난수생성 기능 활용해서 가위바위보 게임 만들기

1. 프로그램 실행 시 콘솔에서 "가위", "바위", "보" 중 1개를 입력받는다.
2. 프로그램 내에서 생성한 0 ~ 2 범위의 난수 1개를 생성하고, 0이면 "가위", 1이면 "바위", 2이면 "보"로 간주한다.
3. 승부 결과를 출력한다.
e.g.
```
$ 가위 바위 보 중 하나를 입력하세요.
> 보
$ 컴퓨터: 바위
$ 사용자: 승!

$ 가위 바위 보 중 하나를 입력하세요.
> 보
$ 컴퓨터: 가위
$ 사용자: 패..ㅠㅠ
```
