### ISSUE TITLE
6. Java Collection Framework (자바 컬렉션 프레임워크) 공부

### ISSUE THREAD

**Issue by HyunGyu-Lee** [HyunGyu-Lee/basic-java#7]

**Comment by KimPro-KR** [comment]
collections Framwork

    1. ArrayList
        - 생성 시 갯수를 지정하지 않는 배열이 생성된다.
        - 선언 방법 : 
            - ArrayList 변수명 = new ArrayList();
                > object 타입으로 저장되기 때문에 값을 변수에 담기 위해서는 형변환이 필요
            - ArrayList<타입> 변수명 = new ArrayList<타입>();
                > ex) ArrayList<String> array = new ArrayList<String>();
                    변수명의 ArrayList에 추가되는 값이 String 데이터타입이라는 것을 제네릭을 통해 지정
                    제네릭을 통해 입력되는 값이 String 이라는 것을 명시
        - 변수명.add() : 데이터 추가
        - 변수명.size() : ArrayList 크기
        - 변수명.get(i) : i번째 데이터 값

    2. collections Framwork(=컨테이터 =값을 담는 그릇)
        컬렉션 
             - Set 
                - HashSet
                - LinkedHashSet
                - TreeSet
             - List
                - ArrayList
                - Vector
                - LinkedList
             - Queue
                - PriorityQueue
        
        MAP
            - SortedMap
                -TreeMap
            - Hashtable
            - LinkedHashMap
            - HashMap
    
        1) List 와 Set의 차이점
            - List의 경우 생성하여 데이터를 추가 하게 되면 중복 상관 없이 그대로 저장을한다.
            - Set의 경우 생성하여 데이터 추가시 중복된 데이터는 고유의 데이터만 저장하고 중복 제거한다.
            - List의 경우 순서가 있기 때문에 index와 관련된 API를 갖고 있으나
              Set의 경우 순서가 없기 때문에 갖고 있지 않다.

**Comment by KimPro-KR** [comment]
3. HashSet
        - Set 은 집합의 의미
        - containsAll :  부분 집합  (A.containsAll(B) : A라는 원소에 B원소 전체가 담겨있는지의 여부)
        - addAll : 합집합  (A.addAll(B) : A 원소에 B 원소 전체를 추가)
        - retainAll : 교집합 (A.retainAll(B) : A와B의 교집합을 A에다가 담기)
        - removeAll : 차집합 (A.removeAll(B) : A에서 B를 뺀 차집합을 A에다가 담기)

4. Iterator()   인터페이스
        - (반복자) 컨테이너에 담겨져 있는 데이터를 하나하나 꺼내서 처리
        - Iterator 변수명 = 변수명.Iterator();
        - hasNext : 변수명 안에 데이터가 있는지의 여부 (true/false)
        - next : 변수명 안에 첫번째 값 1개를 가져온다.
        - Iterator를 사용하면 가상의 저장공간에 데이터가 들어가게되고,
          next를 사용하여 1개의 값을 가져가면 저장공간에서는 그 값이 사라지고
          가져간 다음값이 첫번째 값으로 가게되어 그값을 가져가서 작업한다.

**Comment by HyunGyu-Lee** [comment]
@KimPro-KR 
자료구조에 대해 조사 + 공부하고, 지금까지 공부한 컬렉션들 (Set, List, Map 인터페이스 및 이하 구현체들)이 어떤 자료구조를 구현한 것인지 정리해주세요

**Comment by KimPro-KR** [comment]
5. Map
        - Key 값과 Value 값 2개를 가짐
        - Key 값은 중복이 불가 하며 Value 값은 중복이 가능
        - Key 값이 중복 될 경우 기존 키값은 유지되며 Value 값이 새로운 값으로 변경 되어짐

**Comment by KimPro-KR** [comment]
자료구조로 검색해서 오늘 공부 진행한 내용입니다.

- 스택
    - 입구/출구가 한개인 통, 입구가 하나이기 때문에 한 입구에서 데이터의 추가와 삭제가 이루어짐
    - 가장 나중에 넣은 데이터를 가장 먼저 빼야한다.(LIFO)

- 큐
    - 입구와 출구의 입구가 각각 잇어서 데이터 추가와 제거가 따로 이루어짐
    - 가장 먼저 진입한 데이터가 가장 먼저 나온다.(FIFO)

- 해쉬테이블
    - Key를 갖고 검색을 용이하게 하는 자료 구조
    - 데이터 별로 키값을 갖고 있어 해당 키값으로 검색을 한다.

- ArrayList
    - 배열구조
    - ArrayList<타입> 변수명 = new ArrayList<타입>();
    - 특정 사이즈를 만드는 것이 아니기 때문에 특정사이즈를 만드는 배열에 비해 메모리를 효율적으로 관리 할 수 있다.
    - 데이터 추가, 삭제, 검색에 대한 메소드(add, remove, get, clear 등)가 주어진다.
    - indexOf(인덱스 0부터 데이터 검색), lastIndexOf(현재 ArrayList 중 마지막에서부터 0번째로 오면서 검색)
    - size 메소드를 사용하여 ArrayList의 길이를 반환

- LinkedList
    - 데이터 추가, 삭제, 검색 등 메소드는 ArrayList와 동일
    - 코드 사용법은 ArrayList와 동일하지만 내부적 구조가 틀림
    - 첫번째 생성된 데이터가 root역할을 하며, 그다음 데이터부터는 root를 기준으로 1,2,3 거리로 확인
    

- Iterator
    - 데이터를 순서대로 표시 하기위해 사용
    - hasNext() : 데이터가 있는지의 여부 확인 (while 사용해서 사용)
    - next() : 데이터를 순서대로 표시

- HashMap
    - 해쉬테이블 : 데이터를 저장하는데 키값을 부여하여 키값으로 데이터를 조회하는 자료구조
    - 키값과 데이터값이 있기 때문에 2개의 제네릭이 필요하다.

**Comment by KimPro-KR** [comment]
자료구조에 대해서 질문이 있습니다.
Vector과 ArrayList 의 차이점에 대해서
Vector은 하나의 스레드에만 접근이 가능하고
ArrayList는 다중 스레드 접근이 가능하다고 설명이 되어있는데,
스레드 접근이라는 것이 어떤걸 의미하는지 궁금합니다

**Comment by HyunGyu-Lee** [comment]
@KimPro-KR 
스레드 (Thread) 부분에 대한 공부가 아직 되지 않아서 이해하기 어려울 것으로 생각됩니다.
스레드는 프로그램(프로세스)내에서 이뤄지는 하나의 작업흐름을 의미하며 하나의 프로그램은 여러 가지 작업 흐름(스레드)를 가질 수 있습니다.

예를들면 IntelliJ(프로그램)에서 편집기에 코딩을 하는 동안 백그라운드 작업으로 플러그인을 설치를 진행하는 것을 예로 들 수 있습니다.
또는 뱅킹 프로그램에서 누군가는 인출을 하고 누군가는 예금을 하거나, 동시에 여려 명이 인출을 하는 등의 행위 또한 예가 될 수 있습니다.

스레드가 접근한다는 것은 스레드가 프로그램 내 어떤 자원을 사용(값을 조회하거나 쓰거나)하는 것을 이야기하는데
이 때 여러 스레드가 하나의 자원에 동시에 접근할 경우 문제가 생길 수 있습니다.

아래 상황을 예시로 들어보겠습니다.
자원 : 잔고가 10000원이 들어있는 A계좌
스레드1  : A계좌에서 8000원 출금
스레드2 : A계좌에서 5000원 출금

스레드는 동시에 실행될 수 있는 흐름이기 때문에 두 스레드에서 서로 자원에 접근한 시점에 잔고가 10000원이라면 두 스레드가 출금이 가능한 상황이 되버리고 각각 8000, 5000원을 A계좌에서 차감해 A계좌에 잔고가 -3000원이 되버리는 상황이 생겨버릴 수 도 있습니다.

그렇게 때문에 위과 같은 상황에선 여러 스레드들이 자원에 대해 동시에 처리할 수 없는 방어책이 필요하고 자원을 잠거나 실행 흐름을 잠그는 등의 여러 방법으로 동시 실행을 막습니다.

위에서 얘기한 `Vector은 하나의 스레드에만 접근이 가능`하다는 뜻은 Vector 클래스는 이러한 동시적인 작업에 대한 방어책이 적용되있는 클래스라고 생각하면 됩니다. `ArrayList는 다중 스레드 접근`하다는 뜻은 반대로 이런 방어책이 적용되어있지 않은 클래스겠습니다.

Vector클래스는 동시성 방어가 되는 클래스이기 때문에 작업속도가 ArrayList보다 당연히 느릴수밖에 없기 때문에 각각 장단점이 있습니다.

우선 이 정도로만 생각하고 더 자세한 내용은 이후에 스레드 부분 공부할 때 다시 다루는 거로 하겠습니다.

**Comment by KimPro-KR** [comment]
작성해주신 부분 내용 이해 했습니다. 다중/단일 스레드는 동시성 방어를 위한 부분이고 단일스레드는 다중스레드에 비해 작업속도가 느린 부분입니다. 
금일 자료구조 부분에 대해서 공부했습니다.
계속적으로 자료구조 공부를 진행 할지 어떻게 진행해야할지 말씀부탁드립니다.

**Comment by HyunGyu-Lee** [comment]
@KimPro-KR 
우선 영상보던거 마루미

**Comment by KimPro-KR** [comment]
@HyunGyu-Lee  알람테스트

**Comment by HyunGyu-Lee** [comment]
@KimPro-KR 

## 문제
학생 정보를 `입력` / `조회`할 수 있는 학생 기록부 관리 프로그램 만들기

- 학생 정보
  - 이름 (문자열)
  - 반 (문자열)
  - 나이 (정수)

## 실행 예
```
$ 학생 기록부 관리 프로그램
$ ================
$ 1. 학생 입력
$ 2. 기록부 조회
$ 3. 종료
$ ================
> 2
$ 등록된 학생이 없습니다.
$ ================
$ 1. 학생 입력
$ 2. 기록부 조회
$ 3. 종료
$ ================
> 1
$ 학생 입력을 시작합니다.
$ 이름
> 이현규
$ 반
> A
$ 나이
> 29
$ 등록이 완료되었습니다.
$ ================
$ 1. 학생 입력
$ 2. 기록부 조회
$ 3. 종료
$ ================
> 2
$ 1. 이현규 / A / 29
$ ================
$ 1. 학생 입력
$ 2. 기록부 조회
$ 3. 종료
$ ================
> 3
```

**Comment by KimPro-KR** [comment]
@HyunGyu-Lee 
잘안된 부분과 궁금한 부분
1. 학생의 이름,반,나이를 객체로 해서 arraylist를 선언 하였는데 switch문에서 case실행시 arraylist에 입력받은 값으로 객체를 생성해서 add를 했는데 arraylist에 누적이 안되어지고 실행 될때마다 새로 생성되는데 이부분이 이해가 잘 되지를 않습니다.
해당 부분 관련되서 case1 할때마다 같은 객체로 new로 만들어져서 그런건지 .. 아무리 머리를 짜내도 모르겠다는...

**Comment by HyunGyu-Lee** [comment]
@KimPro-KR 코드가 뭔가 이상한게.. 일단 

```
$ 학생 기록부 관리 프로그램
$ ================
$ 1. 학생 입력
$ 2. 기록부 조회
$ 3. 종료
$ ================
```

이게 반복 수행되는데 반복문이 없는거 부터가 이상함.

일단 지금 푸쉬된 코드가 오류가 발생해서 어느부분이 문제가 있는지 확인하지 못하겠으니
코드 다시한번 확인부탁드림니다

**Comment by KimPro-KR** [comment]
넹

**Comment by KimPro-KR** [comment]
@HyunGyu-Lee 
처음부터 다시 작성해서 푸쉬 했습니다.
확인 부탁드립니다.

**Comment by KimPro-KR** [comment]
@HyunGyu-Lee 
Is anybody there~?

**Comment by HyunGyu-Lee** [comment]
@KimPro-KR 
1. HashSet 활용해보기
- 10이하 랜덤 정수 100개 생성하고 ArrayList와 HashSet에 각각 담고 출력하는 코드 작성
- 결과가 어떻게 나오는지와 왜 결과가 다른지 댓글로 작성

2. HashMap 활용
- 학생 정보
  - 학생번호 (정수)
  - 이름 (문자열)
  - 나이 (정수)
- 학생 정보를 여러 개를 저장하는 코드 작성 (맵은 필수, 다른 컬렉션은 판단하에 선택적으로 사용)
- 학생 정보는 입력하지 말고 그냥 코드상에 직접 써줘도 무방

**Comment by KimPro-KR** [comment]
Arraylist 의 경우에는 순서x 중복x 이며 추가하는대로 다 추가가 되나, Hashset의 경우에는 중복이 불가능하고 인덱스가 존재하지 않는다. 그래서 난수 생성 시 Arraylist 는 100개의 모든 숫자를 다 담는것 이고 Hashset의 경우에는 중복을 제거한 10개의 숫자만 나오게 된다.

**Comment by KimPro-KR** [comment]
@HyunGyu-Lee 
하 일단 hashmap 에서 좀 시간이 많이 소요된부분이 있는데..
문제에서 나는 학생 번호를 hashmap에서의 key값으로 두고,
나머지 값을 arraylist 로 생성해서 hashmap의 value 값으로 쓰려고 한건데
이걸 출력하려고 하니까 너무 어려워서...
일단 꾸역꾸역 출력은 되게 해놧습니다.

**Comment by KimPro-KR** [comment]
@HyunGyu-Lee 
위에 방법과는 다르게 hashmap 만을 사용해서 진행 한 부분 추가합니다.

**Comment by HyunGyu-Lee** [comment]
@KimPro-KR 
- 처음에 올린 예제처럼  value에 ArrayList를 사용하는건 이번  문제에서 불필요한 부분이었음
- 두번째로 올린 keySet 통해 반복문 돌리면서 출력한 방법은 적절
- 피드백 코드에 특정 값을 입력받아 출력하는 기능 추가함
